# TCL File Generated by Component Editor 17.1
# Wed Dec 13 16:45:17 CET 2017
# DO NOT MODIFY


# 
# ValidExtractor "ValidExtractor: Sample Strobe Extractor" v1.0
# Franz Steinbacher 2017.12.13.16:45:17
# Extract the sample strobe of an stream(valid signal) to provide it for other units.
# 

# 
# request TCL package from ACDS 16.1
# 
package require -exact qsys 16.1


# 
# module ValidExtractor
# 
set_module_property DESCRIPTION "Extract the sample strobe of an stream(valid signal) to provide it for other units."
set_module_property NAME ValidExtractor
set_module_property VERSION 1.0
set_module_property INTERNAL false
set_module_property OPAQUE_ADDRESS_MAP true
set_module_property GROUP "ASP-SoC IP/Stream"
set_module_property AUTHOR "Franz Steinbacher"
set_module_property DISPLAY_NAME "ValidExtractor: Sample Strobe Extractor"
set_module_property INSTANTIATE_IN_SYSTEM_MODULE true
set_module_property EDITABLE false
set_module_property REPORT_TO_TALKBACK false
set_module_property ALLOW_GREYBOX_GENERATION false
set_module_property REPORT_HIERARCHY false


# 
# file sets
# 
add_fileset QUARTUS_SYNTH QUARTUS_SYNTH "" ""
set_fileset_property QUARTUS_SYNTH TOP_LEVEL ValidExtractor
set_fileset_property QUARTUS_SYNTH ENABLE_RELATIVE_INCLUDE_PATHS false
set_fileset_property QUARTUS_SYNTH ENABLE_FILE_OVERWRITE_MODE false
add_fileset_file ValidExtractor-ea.vhd VHDL PATH ../hdl/ValidExtractor-ea.vhd TOP_LEVEL_FILE


# 
# parameters
# 
add_parameter data_width_g NATURAL 24
set_parameter_property data_width_g DEFAULT_VALUE 24
set_parameter_property data_width_g DISPLAY_NAME "Data Width"
set_parameter_property data_width_g TYPE NATURAL
set_parameter_property data_width_g ALLOWED_RANGES {8 16 24 32}
set_parameter_property data_width_g UNITS bits
set_parameter_property data_width_g HDL_PARAMETER true


# 
# display items
# 


# 
# connection point clock
# 
add_interface clock clock end
set_interface_property clock clockRate 0
set_interface_property clock ENABLED true
set_interface_property clock EXPORT_OF ""
set_interface_property clock PORT_NAME_MAP ""
set_interface_property clock CMSIS_SVD_VARIABLES ""
set_interface_property clock SVD_ADDRESS_GROUP ""

add_interface_port clock csi_clk clk Input 1


# 
# connection point reset
# 
add_interface reset reset end
set_interface_property reset associatedClock clock
set_interface_property reset synchronousEdges DEASSERT
set_interface_property reset ENABLED true
set_interface_property reset EXPORT_OF ""
set_interface_property reset PORT_NAME_MAP ""
set_interface_property reset CMSIS_SVD_VARIABLES ""
set_interface_property reset SVD_ADDRESS_GROUP ""

add_interface_port reset rsi_reset_n reset_n Input 1


# 
# connection point sink
# 
add_interface sink avalon_streaming end
set_interface_property sink associatedClock clock
set_interface_property sink associatedReset reset
set_interface_property sink dataBitsPerSymbol 8
set_interface_property sink errorDescriptor ""
set_interface_property sink firstSymbolInHighOrderBits true
set_interface_property sink maxChannel 0
set_interface_property sink readyLatency 0
set_interface_property sink ENABLED true
set_interface_property sink EXPORT_OF ""
set_interface_property sink PORT_NAME_MAP ""
set_interface_property sink CMSIS_SVD_VARIABLES ""
set_interface_property sink SVD_ADDRESS_GROUP ""

add_interface_port sink asi_valid valid Input 1
add_interface_port sink asi_data data Input data_width_g


# 
# connection point strobe
# 
add_interface strobe conduit end
set_interface_property strobe associatedClock clock
set_interface_property strobe associatedReset reset
set_interface_property strobe ENABLED true
set_interface_property strobe EXPORT_OF ""
set_interface_property strobe PORT_NAME_MAP ""
set_interface_property strobe CMSIS_SVD_VARIABLES ""
set_interface_property strobe SVD_ADDRESS_GROUP ""

add_interface_port strobe coe_sample_strobe export Output 1


# 
# connection point source
# 
add_interface source avalon_streaming start
set_interface_property source associatedClock clock
set_interface_property source associatedReset reset
set_interface_property source dataBitsPerSymbol 8
set_interface_property source errorDescriptor ""
set_interface_property source firstSymbolInHighOrderBits true
set_interface_property source maxChannel 0
set_interface_property source readyLatency 0
set_interface_property source ENABLED true
set_interface_property source EXPORT_OF ""
set_interface_property source PORT_NAME_MAP ""
set_interface_property source CMSIS_SVD_VARIABLES ""
set_interface_property source SVD_ADDRESS_GROUP ""

add_interface_port source aso_valid valid Output 1
add_interface_port source aso_data data Output data_width_g

