# TCL File Generated by Component Editor 16.1
# Tue Dec 12 15:15:00 CET 2017
# DO NOT MODIFY


# 
# I2S_Codec_Pin_Multiplex "I2S Codec Pin Mux" v1.0
#  2017.12.12.15:15:00
# 
# 

# 
# request TCL package from ACDS 16.1
# 
package require -exact qsys 16.1


# 
# module I2S_Codec_Pin_Multiplex
# 
set_module_property DESCRIPTION ""
set_module_property NAME I2S_Codec_Pin_Multiplex
set_module_property VERSION 1.0
set_module_property INTERNAL false
set_module_property OPAQUE_ADDRESS_MAP true
set_module_property GROUP "ASP-SoC IP/Audio"
set_module_property AUTHOR ""
set_module_property DISPLAY_NAME "I2S Codec Pin Mux"
set_module_property INSTANTIATE_IN_SYSTEM_MODULE true
set_module_property EDITABLE true
set_module_property REPORT_TO_TALKBACK false
set_module_property ALLOW_GREYBOX_GENERATION false
set_module_property REPORT_HIERARCHY false


# 
# file sets
# 
add_fileset QUARTUS_SYNTH QUARTUS_SYNTH "" ""
set_fileset_property QUARTUS_SYNTH TOP_LEVEL CodecPinMux
set_fileset_property QUARTUS_SYNTH ENABLE_RELATIVE_INCLUDE_PATHS false
set_fileset_property QUARTUS_SYNTH ENABLE_FILE_OVERWRITE_MODE false
add_fileset_file CodecPinMux-Rtl-a.vhd VHDL PATH ../../../grpAudioCodec/unitCodecPinMux/hdl/CodecPinMux-Rtl-a.vhd
add_fileset_file CodecPinMux-e.vhd VHDL PATH ../../../grpAudioCodec/unitCodecPinMux/hdl/CodecPinMux-e.vhd TOP_LEVEL_FILE

add_fileset SIM_VERILOG SIM_VERILOG "" ""
set_fileset_property SIM_VERILOG TOP_LEVEL CodecPinMux
set_fileset_property SIM_VERILOG ENABLE_RELATIVE_INCLUDE_PATHS false
set_fileset_property SIM_VERILOG ENABLE_FILE_OVERWRITE_MODE false
add_fileset_file CodecPinMux-Rtl-a.vhd VHDL PATH ../../../grpAudioCodec/unitCodecPinMux/hdl/CodecPinMux-Rtl-a.vhd
add_fileset_file CodecPinMux-e.vhd VHDL PATH ../../../grpAudioCodec/unitCodecPinMux/hdl/CodecPinMux-e.vhd

add_fileset SIM_VHDL SIM_VHDL "" ""
set_fileset_property SIM_VHDL TOP_LEVEL CodecPinMux
set_fileset_property SIM_VHDL ENABLE_RELATIVE_INCLUDE_PATHS false
set_fileset_property SIM_VHDL ENABLE_FILE_OVERWRITE_MODE false
add_fileset_file CodecPinMux-Rtl-a.vhd VHDL PATH ../../../grpAudioCodec/unitCodecPinMux/hdl/CodecPinMux-Rtl-a.vhd
add_fileset_file CodecPinMux-e.vhd VHDL PATH ../../../grpAudioCodec/unitCodecPinMux/hdl/CodecPinMux-e.vhd


# 
# parameters
# 
add_parameter gDataWidth NATURAL 24
set_parameter_property gDataWidth DEFAULT_VALUE 24
set_parameter_property gDataWidth DISPLAY_NAME gDataWidth
set_parameter_property gDataWidth TYPE NATURAL
set_parameter_property gDataWidth UNITS None
set_parameter_property gDataWidth ALLOWED_RANGES 0:2147483647
set_parameter_property gDataWidth HDL_PARAMETER true
add_parameter gDataWidthLen NATURAL 5
set_parameter_property gDataWidthLen DEFAULT_VALUE 5
set_parameter_property gDataWidthLen DISPLAY_NAME gDataWidthLen
set_parameter_property gDataWidthLen TYPE NATURAL
set_parameter_property gDataWidthLen UNITS None
set_parameter_property gDataWidthLen ALLOWED_RANGES 0:2147483647
set_parameter_property gDataWidthLen HDL_PARAMETER true


# 
# display items
# 


# 
# connection point s0
# 
add_interface s0 avalon end
set_interface_property s0 addressUnits WORDS
set_interface_property s0 associatedClock clock_sink
set_interface_property s0 associatedReset reset_sink
set_interface_property s0 bitsPerSymbol 8
set_interface_property s0 burstOnBurstBoundariesOnly false
set_interface_property s0 burstcountUnits WORDS
set_interface_property s0 explicitAddressSpan 0
set_interface_property s0 holdTime 0
set_interface_property s0 linewrapBursts false
set_interface_property s0 maximumPendingReadTransactions 0
set_interface_property s0 maximumPendingWriteTransactions 0
set_interface_property s0 readLatency 0
set_interface_property s0 readWaitTime 1
set_interface_property s0 setupTime 0
set_interface_property s0 timingUnits Cycles
set_interface_property s0 writeWaitTime 0
set_interface_property s0 ENABLED true
set_interface_property s0 EXPORT_OF ""
set_interface_property s0 PORT_NAME_MAP ""
set_interface_property s0 CMSIS_SVD_VARIABLES ""
set_interface_property s0 SVD_ADDRESS_GROUP ""

add_interface_port s0 avs_s0_write write Input 1
add_interface_port s0 avs_s0_writedata writedata Input 32
set_interface_assignment s0 embeddedsw.configuration.isFlash 0
set_interface_assignment s0 embeddedsw.configuration.isMemoryDevice 0
set_interface_assignment s0 embeddedsw.configuration.isNonVolatileStorage 0
set_interface_assignment s0 embeddedsw.configuration.isPrintableDevice 0


# 
# connection point clock_sink
# 
add_interface clock_sink clock end
set_interface_property clock_sink clockRate 0
set_interface_property clock_sink ENABLED true
set_interface_property clock_sink EXPORT_OF ""
set_interface_property clock_sink PORT_NAME_MAP ""
set_interface_property clock_sink CMSIS_SVD_VARIABLES ""
set_interface_property clock_sink SVD_ADDRESS_GROUP ""

add_interface_port clock_sink iClk clk Input 1


# 
# connection point reset_sink
# 
add_interface reset_sink reset end
set_interface_property reset_sink associatedClock clock_sink
set_interface_property reset_sink synchronousEdges DEASSERT
set_interface_property reset_sink ENABLED true
set_interface_property reset_sink EXPORT_OF ""
set_interface_property reset_sink PORT_NAME_MAP ""
set_interface_property reset_sink CMSIS_SVD_VARIABLES ""
set_interface_property reset_sink SVD_ADDRESS_GROUP ""

add_interface_port reset_sink inReset reset_n Input 1


# 
# connection point IF_GPIO
# 
add_interface IF_GPIO conduit end
set_interface_property IF_GPIO associatedClock clock_sink
set_interface_property IF_GPIO associatedReset reset_sink
set_interface_property IF_GPIO ENABLED true
set_interface_property IF_GPIO EXPORT_OF ""
set_interface_property IF_GPIO PORT_NAME_MAP ""
set_interface_property IF_GPIO CMSIS_SVD_VARIABLES ""
set_interface_property IF_GPIO SVD_ADDRESS_GROUP ""

add_interface_port IF_GPIO iADCDAT_GPIO iadcdat Input 1
add_interface_port IF_GPIO iADCLRC_GPIO iadclrc Input 1
add_interface_port IF_GPIO iBCLK_GPIO ibclk Input 1
add_interface_port IF_GPIO iDACLRC_GPIO idaclrc Input 1
add_interface_port IF_GPIO oDACDAT_GPIO odacdat Output 1


# 
# connection point IF_CODEC
# 
add_interface IF_CODEC conduit end
set_interface_property IF_CODEC associatedClock clock_sink
set_interface_property IF_CODEC associatedReset reset_sink
set_interface_property IF_CODEC ENABLED true
set_interface_property IF_CODEC EXPORT_OF ""
set_interface_property IF_CODEC PORT_NAME_MAP ""
set_interface_property IF_CODEC CMSIS_SVD_VARIABLES ""
set_interface_property IF_CODEC SVD_ADDRESS_GROUP ""

add_interface_port IF_CODEC iADCDAT_CODEC iadcdat Input 1
add_interface_port IF_CODEC iADCLRC_CODEC iadclrc Input 1
add_interface_port IF_CODEC iBCLK_CODEC ibclk Input 1
add_interface_port IF_CODEC iDACLRC_CODEC idaclrc Input 1
add_interface_port IF_CODEC oDACDAT_CODEC odacdat Output 1


# 
# connection point IF_SYSTEM
# 
add_interface IF_SYSTEM conduit end
set_interface_property IF_SYSTEM associatedClock clock_sink
set_interface_property IF_SYSTEM associatedReset ""
set_interface_property IF_SYSTEM ENABLED true
set_interface_property IF_SYSTEM EXPORT_OF ""
set_interface_property IF_SYSTEM PORT_NAME_MAP ""
set_interface_property IF_SYSTEM CMSIS_SVD_VARIABLES ""
set_interface_property IF_SYSTEM SVD_ADDRESS_GROUP ""

add_interface_port IF_SYSTEM oADCDAT adcdat Output 1
add_interface_port IF_SYSTEM oADCLRC adclrck Output 1
add_interface_port IF_SYSTEM oBCLK bclk Output 1
add_interface_port IF_SYSTEM oDACLRC daclrck Output 1
add_interface_port IF_SYSTEM iDACDAT dacdat Input 1

