# TCL File Generated by Component Editor 17.1
# Tue Dec 19 14:52:30 CET 2017
# DO NOT MODIFY


# 
# AddChannels "AddChannels: Add Streaming Channels" v1.0
# Franz Steinbacher 2017.12.19.14:52:30
# Add two streaming channels
# 

# 
# request TCL package from ACDS 16.1
# 
package require -exact qsys 16.1


# 
# module AddChannels
# 
set_module_property DESCRIPTION "Add two streaming channels"
set_module_property NAME AddChannels
set_module_property VERSION 1.0
set_module_property INTERNAL false
set_module_property OPAQUE_ADDRESS_MAP true
set_module_property GROUP "ASP-SoC IP/Dsp"
set_module_property AUTHOR "Franz Steinbacher"
set_module_property DISPLAY_NAME "AddChannels: Add Streaming Channels"
set_module_property INSTANTIATE_IN_SYSTEM_MODULE true
set_module_property EDITABLE false
set_module_property REPORT_TO_TALKBACK false
set_module_property ALLOW_GREYBOX_GENERATION false
set_module_property REPORT_HIERARCHY false


# 
# file sets
# 
add_fileset QUARTUS_SYNTH QUARTUS_SYNTH "" ""
set_fileset_property QUARTUS_SYNTH TOP_LEVEL AddChannels
set_fileset_property QUARTUS_SYNTH ENABLE_RELATIVE_INCLUDE_PATHS false
set_fileset_property QUARTUS_SYNTH ENABLE_FILE_OVERWRITE_MODE false
add_fileset_file AddChannels-ea.vhd VHDL PATH ../hdl/AddChannels-ea.vhd TOP_LEVEL_FILE
add_fileset_file fixed_float_types_c.vhdl VHDL PATH ../../../grpPackages/pkgFixed/src/fixed_float_types_c.vhdl
add_fileset_file fixed_pkg_c.vhdl VHDL PATH ../../../grpPackages/pkgFixed/src/fixed_pkg_c.vhdl


# 
# parameters
# 
add_parameter data_width_g NATURAL 24 
set_parameter_property data_width_g DEFAULT_VALUE 24
set_parameter_property data_width_g DISPLAY_NAME "Data Width"
set_parameter_property data_width_g TYPE NATURAL
set_parameter_property data_width_g UNITS bits
set_parameter_property data_width_g ALLOWED_RANGES {16 20 24 32}
set_parameter_property data_width_g DESCRIPTION "Audio Data Width"
set_parameter_property data_width_g HDL_PARAMETER true

# 
# display items
# 


# 
# connection point clock
# 
add_interface clock clock end
set_interface_property clock clockRate 0
set_interface_property clock ENABLED true
set_interface_property clock EXPORT_OF ""
set_interface_property clock PORT_NAME_MAP ""
set_interface_property clock CMSIS_SVD_VARIABLES ""
set_interface_property clock SVD_ADDRESS_GROUP ""

add_interface_port clock csi_clk clk Input 1


# 
# connection point reset
# 
add_interface reset reset end
set_interface_property reset associatedClock clock
set_interface_property reset synchronousEdges DEASSERT
set_interface_property reset ENABLED true
set_interface_property reset EXPORT_OF ""
set_interface_property reset PORT_NAME_MAP ""
set_interface_property reset CMSIS_SVD_VARIABLES ""
set_interface_property reset SVD_ADDRESS_GROUP ""

add_interface_port reset rsi_reset_n reset_n Input 1


# 
# connection point source
# 
add_interface source avalon_streaming start
set_interface_property source associatedClock clock
set_interface_property source associatedReset reset
set_interface_property source dataBitsPerSymbol 8
set_interface_property source errorDescriptor ""
set_interface_property source firstSymbolInHighOrderBits true
set_interface_property source maxChannel 0
set_interface_property source readyLatency 0
set_interface_property source ENABLED true
set_interface_property source EXPORT_OF ""
set_interface_property source PORT_NAME_MAP ""
set_interface_property source CMSIS_SVD_VARIABLES ""
set_interface_property source SVD_ADDRESS_GROUP ""

add_interface_port source aso_data data Output data_width_g
add_interface_port source aso_valid valid Output 1


# 
# connection point sink_a
# 
add_interface sink_a avalon_streaming end
set_interface_property sink_a associatedClock clock
set_interface_property sink_a associatedReset reset
set_interface_property sink_a dataBitsPerSymbol 8
set_interface_property sink_a errorDescriptor ""
set_interface_property sink_a firstSymbolInHighOrderBits true
set_interface_property sink_a maxChannel 0
set_interface_property sink_a readyLatency 0
set_interface_property sink_a ENABLED true
set_interface_property sink_a EXPORT_OF ""
set_interface_property sink_a PORT_NAME_MAP ""
set_interface_property sink_a CMSIS_SVD_VARIABLES ""
set_interface_property sink_a SVD_ADDRESS_GROUP ""

add_interface_port sink_a asi_a_data data Input data_width_g
add_interface_port sink_a asi_a_valid valid Input 1


# 
# connection point sink_b
# 
add_interface sink_b avalon_streaming end
set_interface_property sink_b associatedClock clock
set_interface_property sink_b associatedReset reset
set_interface_property sink_b dataBitsPerSymbol 8
set_interface_property sink_b errorDescriptor ""
set_interface_property sink_b firstSymbolInHighOrderBits true
set_interface_property sink_b maxChannel 0
set_interface_property sink_b readyLatency 0
set_interface_property sink_b ENABLED true
set_interface_property sink_b EXPORT_OF ""
set_interface_property sink_b PORT_NAME_MAP ""
set_interface_property sink_b CMSIS_SVD_VARIABLES ""
set_interface_property sink_b SVD_ADDRESS_GROUP ""

add_interface_port sink_b asi_b_data data Input data_width_g
add_interface_port sink_b asi_b_valid valid Input 1

