# TCL File Generated by Component Editor 16.1
# Tue May 23 20:04:40 CEST 2017
# DO NOT MODIFY


# 
# AudioCodecAvalon "AudioCodecAvalon" v1.0
# Franz Steinbacher 2017.05.23.20:04:40
# Audio Codec to Avalon ST Interface
# 

# 
# request TCL package from ACDS 16.1
# 
package require -exact qsys 16.1

proc NrBitsNeeded {x} {expr int(ceil(log($x)/log(2)))}


# 
# module AudioCodecAvalon
# 
set_module_property DESCRIPTION "Audio Codec to Avalon ST Interface"
set_module_property NAME AudioCodecAvalon
set_module_property VERSION 1.0
set_module_property INTERNAL false
set_module_property OPAQUE_ADDRESS_MAP true
set_module_property GROUP "ASP-SoC IP/Audio"
set_module_property AUTHOR "Franz Steinbacher"
set_module_property DISPLAY_NAME "AudioCodecAvalon: Audio Codec to Avalon ST"
set_module_property INSTANTIATE_IN_SYSTEM_MODULE true
set_module_property EDITABLE false
set_module_property REPORT_TO_TALKBACK false
set_module_property ALLOW_GREYBOX_GENERATION false
set_module_property REPORT_HIERARCHY false

set_module_property ELABORATION_CALLBACK elaborate


# 
# file sets
# 
add_fileset QUARTUS_SYNTH QUARTUS_SYNTH "" ""
set_fileset_property QUARTUS_SYNTH TOP_LEVEL AudioCodecAvalon
set_fileset_property QUARTUS_SYNTH ENABLE_RELATIVE_INCLUDE_PATHS false
set_fileset_property QUARTUS_SYNTH ENABLE_FILE_OVERWRITE_MODE false
add_fileset_file AudioCodecAvalon-e.vhd VHDL PATH ../hdl/AudioCodecAvalon-e.vhd TOP_LEVEL_FILE
add_fileset_file AudioCodecAvalon-Struct-a.vhd VHDL PATH ../hdl/AudioCodecAvalon-Struct-a.vhd
add_fileset_file AvalonSTToI2S-Rtl-a.vhd VHDL PATH ../../unitAvalonSTToI2S/hdl/AvalonSTToI2S-Rtl-a.vhd
add_fileset_file AvalonSTToI2S-e.vhd VHDL PATH ../../unitAvalonSTToI2S/hdl/AvalonSTToI2S-e.vhd
add_fileset_file I2SToAvalonST-Rtl-a.vhd VHDL PATH ../../unitI2SToAvalonST/hdl/I2SToAvalonST-Rtl-a.vhd
add_fileset_file I2SToAvalonST-e.vhd VHDL PATH ../../unitI2SToAvalonST/hdl/I2SToAvalonST-e.vhd

add_fileset SIM_VHDL SIM_VHDL "" ""
set_fileset_property SIM_VHDL TOP_LEVEL AudioCodecAvalon
set_fileset_property SIM_VHDL ENABLE_RELATIVE_INCLUDE_PATHS false
set_fileset_property SIM_VHDL ENABLE_FILE_OVERWRITE_MODE false
add_fileset_file AudioCodecAvalon-e.vhd VHDL PATH ../hdl/AudioCodecAvalon-e.vhd
add_fileset_file AudioCodecAvalon-Struct-a.vhd VHDL PATH ../hdl/AudioCodecAvalon-Struct-a.vhd
add_fileset_file AvalonSTToI2S-Rtl-a.vhd VHDL PATH ../../unitAvalonSTToI2S/hdl/AvalonSTToI2S-Rtl-a.vhd
add_fileset_file AvalonSTToI2S-e.vhd VHDL PATH ../../unitAvalonSTToI2S/hdl/AvalonSTToI2S-e.vhd
add_fileset_file I2SToAvalonST-Rtl-a.vhd VHDL PATH ../../unitI2SToAvalonST/hdl/I2SToAvalonST-Rtl-a.vhd
add_fileset_file I2SToAvalonST-e.vhd VHDL PATH ../../unitI2SToAvalonST/hdl/I2SToAvalonST-e.vhd


# 
# parameters
# 
add_parameter gDataWidth NATURAL 24 
set_parameter_property gDataWidth DEFAULT_VALUE 24
set_parameter_property gDataWidth DISPLAY_NAME gDataWidth
set_parameter_property gDataWidth DESCRIPTION \
    "Number of Data Bits"
set_parameter_property gDataWidth LONG_DESCRIPTION \
    "Number of Data Bits"
set_parameter_property gDataWidth WIDTH ""
set_parameter_property gDataWidth TYPE NATURAL
set_parameter_property gDataWidth UNITS None
set_parameter_property gDataWidth ALLOWED_RANGES {16 20 24 32}
set_parameter_property gDataWidth HDL_PARAMETER true

add_parameter gDataWidthLen NATURAL 5
set_parameter_property gDataWidthLen DEFAULT_VALUE 5
set_parameter_property gDataWidthLen DISPLAY_NAME gDataWidthLen
set_parameter_property gDataWidthLen DESCRIPTION \
    "Automatically computed from gDataWidth"
set_parameter_property gDataWidthLen LONG_DESCRIPTION \
    "Automatically computed from gDataWidth"
set_parameter_property gDataWidthLen TYPE NATURAL
set_parameter_property gDataWidthLen ENABLED false
set_parameter_property gDataWidthLen UNITS None
set_parameter_property gDataWidthLen HDL_PARAMETER true
set_parameter_property gDataWidthLen DERIVED true


proc elaborate {} {
set DataWidth [ get_parameter_value "gDataWidth" ]
set DataWidthLen [ NrBitsNeeded $DataWidth ]
set_parameter_value gDataWidthLen $DataWidthLen
send_message { Info Text } "Elaboration just took place. Nr of Bits for DataWidth $DataWidthLen ."
}

# 
# display items
# 



# 
# connection point clock
# 
add_interface clock clock end
set_interface_property clock clockRate 0
set_interface_property clock ENABLED true
set_interface_property clock EXPORT_OF ""
set_interface_property clock PORT_NAME_MAP ""
set_interface_property clock CMSIS_SVD_VARIABLES ""
set_interface_property clock SVD_ADDRESS_GROUP ""

add_interface_port clock csi_clk clk Input 1


# 
# connection point reset
# 
add_interface reset reset end
set_interface_property reset associatedClock clock
set_interface_property reset synchronousEdges DEASSERT
set_interface_property reset ENABLED true
set_interface_property reset EXPORT_OF ""
set_interface_property reset PORT_NAME_MAP ""
set_interface_property reset CMSIS_SVD_VARIABLES ""
set_interface_property reset SVD_ADDRESS_GROUP ""

add_interface_port reset rsi_reset_n reset_n Input 1


# 
# connection point conduit_end
# 
add_interface conduit_end conduit end
set_interface_property conduit_end associatedClock clock
set_interface_property conduit_end associatedReset ""
set_interface_property conduit_end ENABLED true
set_interface_property conduit_end EXPORT_OF ""
set_interface_property conduit_end PORT_NAME_MAP ""
set_interface_property conduit_end CMSIS_SVD_VARIABLES ""
set_interface_property conduit_end SVD_ADDRESS_GROUP ""

add_interface_port conduit_end AUD_ADCDAT adcdat Input 1
add_interface_port conduit_end AUD_ADCLRCK adclrck Input 1
add_interface_port conduit_end AUD_BCLK bclk Input 1
add_interface_port conduit_end AUD_DACDAT dacdat Output 1
add_interface_port conduit_end AUD_DACLRCK daclrck Input 1


# 
# connection point left_sink
# 
add_interface left_sink avalon_streaming end
set_interface_property left_sink associatedClock clock
set_interface_property left_sink associatedReset reset
set_interface_property left_sink dataBitsPerSymbol 8
set_interface_property left_sink errorDescriptor ""
set_interface_property left_sink firstSymbolInHighOrderBits true
set_interface_property left_sink maxChannel 0
set_interface_property left_sink readyLatency 0
set_interface_property left_sink ENABLED true
set_interface_property left_sink EXPORT_OF ""
set_interface_property left_sink PORT_NAME_MAP ""
set_interface_property left_sink CMSIS_SVD_VARIABLES ""
set_interface_property left_sink SVD_ADDRESS_GROUP ""

add_interface_port left_sink asi_left_data data Input gDataWidth
add_interface_port left_sink asi_left_valid valid Input 1


# 
# connection point right_sink
# 
add_interface right_sink avalon_streaming end
set_interface_property right_sink associatedClock clock
set_interface_property right_sink associatedReset reset
set_interface_property right_sink dataBitsPerSymbol 8
set_interface_property right_sink errorDescriptor ""
set_interface_property right_sink firstSymbolInHighOrderBits true
set_interface_property right_sink maxChannel 0
set_interface_property right_sink readyLatency 0
set_interface_property right_sink ENABLED true
set_interface_property right_sink EXPORT_OF ""
set_interface_property right_sink PORT_NAME_MAP ""
set_interface_property right_sink CMSIS_SVD_VARIABLES ""
set_interface_property right_sink SVD_ADDRESS_GROUP ""

add_interface_port right_sink asi_right_data data Input gdatawidth
add_interface_port right_sink asi_right_valid valid Input 1


# 
# connection point left_source
# 
add_interface left_source avalon_streaming start
set_interface_property left_source associatedClock clock
set_interface_property left_source associatedReset reset
set_interface_property left_source dataBitsPerSymbol 8
set_interface_property left_source errorDescriptor ""
set_interface_property left_source firstSymbolInHighOrderBits true
set_interface_property left_source maxChannel 0
set_interface_property left_source readyLatency 0
set_interface_property left_source ENABLED true
set_interface_property left_source EXPORT_OF ""
set_interface_property left_source PORT_NAME_MAP ""
set_interface_property left_source CMSIS_SVD_VARIABLES ""
set_interface_property left_source SVD_ADDRESS_GROUP ""

add_interface_port left_source aso_left_data data Output gdatawidth
add_interface_port left_source aso_left_valid valid Output 1


# 
# connection point right_source
# 
add_interface right_source avalon_streaming start
set_interface_property right_source associatedClock clock
set_interface_property right_source associatedReset reset
set_interface_property right_source dataBitsPerSymbol 8
set_interface_property right_source errorDescriptor ""
set_interface_property right_source firstSymbolInHighOrderBits true
set_interface_property right_source maxChannel 0
set_interface_property right_source readyLatency 0
set_interface_property right_source ENABLED true
set_interface_property right_source EXPORT_OF ""
set_interface_property right_source PORT_NAME_MAP ""
set_interface_property right_source CMSIS_SVD_VARIABLES ""
set_interface_property right_source SVD_ADDRESS_GROUP ""

add_interface_port right_source aso_right_data data Output gdatawidth
add_interface_port right_source aso_right_valid valid Output 1

