# TCL File Generated by Component Editor 16.1
# Tue Mar 14 19:57:06 CET 2017
# DO NOT MODIFY


# 
# AudioAvalonStream "audio_avalon_stream" v1.0
# Franz Steinbacher 2017.03.14.19:57:06
# streams the 4 channels from audio codec as 2 channels
# 

# 
# request TCL package from ACDS 16.1
# 
package require -exact qsys 16.1


# 
# module AudioAvalonStream
# 
set_module_property DESCRIPTION "streams the 4 channels from audio codec as 2 channels"
set_module_property NAME AudioAvalonStream
set_module_property VERSION 1.0
set_module_property INTERNAL false
set_module_property OPAQUE_ADDRESS_MAP true
set_module_property GROUP "My Own IP Cores"
set_module_property AUTHOR "Franz Steinbacher"
set_module_property DISPLAY_NAME audio_avalon_stream
set_module_property INSTANTIATE_IN_SYSTEM_MODULE true
set_module_property EDITABLE true
set_module_property REPORT_TO_TALKBACK false
set_module_property ALLOW_GREYBOX_GENERATION false
set_module_property REPORT_HIERARCHY false


# 
# file sets
# 
add_fileset QUARTUS_SYNTH QUARTUS_SYNTH "" ""
set_fileset_property QUARTUS_SYNTH TOP_LEVEL AudioAvalonStream
set_fileset_property QUARTUS_SYNTH ENABLE_RELATIVE_INCLUDE_PATHS false
set_fileset_property QUARTUS_SYNTH ENABLE_FILE_OVERWRITE_MODE false
add_fileset_file AudioAvalonStream-Struct-ea.vhd VHDL PATH ../../unitAudioAvalonStream/src/AudioAvalonStream-Struct-ea.vhd TOP_LEVEL_FILE

add_fileset SIM_VHDL SIM_VHDL "" ""
set_fileset_property SIM_VHDL TOP_LEVEL AudioAvalonStream
set_fileset_property SIM_VHDL ENABLE_RELATIVE_INCLUDE_PATHS false
set_fileset_property SIM_VHDL ENABLE_FILE_OVERWRITE_MODE false
add_fileset_file AudioAvalonStream-Struct-ea.vhd VHDL PATH ../../unitAudioAvalonStream/src/AudioAvalonStream-Struct-ea.vhd


# 
# parameters
# 


# 
# display items
# 


# 
# connection point clock
# 
add_interface clock clock end
set_interface_property clock clockRate 0
set_interface_property clock ENABLED true
set_interface_property clock EXPORT_OF ""
set_interface_property clock PORT_NAME_MAP ""
set_interface_property clock CMSIS_SVD_VARIABLES ""
set_interface_property clock SVD_ADDRESS_GROUP ""

add_interface_port clock clk clk Input 1


# 
# connection point reset
# 
add_interface reset reset end
set_interface_property reset associatedClock clock
set_interface_property reset synchronousEdges DEASSERT
set_interface_property reset ENABLED true
set_interface_property reset EXPORT_OF ""
set_interface_property reset PORT_NAME_MAP ""
set_interface_property reset CMSIS_SVD_VARIABLES ""
set_interface_property reset SVD_ADDRESS_GROUP ""

add_interface_port reset reset reset_n Input 1


# 
# connection point audio_left_channel_sink
# 
add_interface audio_left_channel_sink avalon_streaming end
set_interface_property audio_left_channel_sink associatedClock clock
set_interface_property audio_left_channel_sink associatedReset reset
set_interface_property audio_left_channel_sink dataBitsPerSymbol 8
set_interface_property audio_left_channel_sink errorDescriptor ""
set_interface_property audio_left_channel_sink firstSymbolInHighOrderBits true
set_interface_property audio_left_channel_sink maxChannel 0
set_interface_property audio_left_channel_sink readyLatency 0
set_interface_property audio_left_channel_sink ENABLED true
set_interface_property audio_left_channel_sink EXPORT_OF ""
set_interface_property audio_left_channel_sink PORT_NAME_MAP ""
set_interface_property audio_left_channel_sink CMSIS_SVD_VARIABLES ""
set_interface_property audio_left_channel_sink SVD_ADDRESS_GROUP ""

add_interface_port audio_left_channel_sink from_audio_left_channel_data data Input 24
add_interface_port audio_left_channel_sink from_audio_left_channel_ready ready Output 1
add_interface_port audio_left_channel_sink from_audio_left_channel_valid valid Input 1


# 
# connection point audio_right_channel_sink
# 
add_interface audio_right_channel_sink avalon_streaming end
set_interface_property audio_right_channel_sink associatedClock clock
set_interface_property audio_right_channel_sink associatedReset reset
set_interface_property audio_right_channel_sink dataBitsPerSymbol 8
set_interface_property audio_right_channel_sink errorDescriptor ""
set_interface_property audio_right_channel_sink firstSymbolInHighOrderBits true
set_interface_property audio_right_channel_sink maxChannel 0
set_interface_property audio_right_channel_sink readyLatency 0
set_interface_property audio_right_channel_sink ENABLED true
set_interface_property audio_right_channel_sink EXPORT_OF ""
set_interface_property audio_right_channel_sink PORT_NAME_MAP ""
set_interface_property audio_right_channel_sink CMSIS_SVD_VARIABLES ""
set_interface_property audio_right_channel_sink SVD_ADDRESS_GROUP ""

add_interface_port audio_right_channel_sink from_audio_right_channel_data data Input 24
add_interface_port audio_right_channel_sink from_audio_right_channel_ready ready Output 1
add_interface_port audio_right_channel_sink from_audio_right_channel_valid valid Input 1


# 
# connection point audio_left_channel_source
# 
add_interface audio_left_channel_source avalon_streaming start
set_interface_property audio_left_channel_source associatedClock clock
set_interface_property audio_left_channel_source associatedReset reset
set_interface_property audio_left_channel_source dataBitsPerSymbol 8
set_interface_property audio_left_channel_source errorDescriptor ""
set_interface_property audio_left_channel_source firstSymbolInHighOrderBits true
set_interface_property audio_left_channel_source maxChannel 0
set_interface_property audio_left_channel_source readyLatency 0
set_interface_property audio_left_channel_source ENABLED true
set_interface_property audio_left_channel_source EXPORT_OF ""
set_interface_property audio_left_channel_source PORT_NAME_MAP ""
set_interface_property audio_left_channel_source CMSIS_SVD_VARIABLES ""
set_interface_property audio_left_channel_source SVD_ADDRESS_GROUP ""

add_interface_port audio_left_channel_source to_audio_left_channel_data data Output 24
add_interface_port audio_left_channel_source to_audio_left_channel_ready ready Input 1
add_interface_port audio_left_channel_source to_audio_left_channel_valid valid Output 1


# 
# connection point audio_right_channel_source
# 
add_interface audio_right_channel_source avalon_streaming start
set_interface_property audio_right_channel_source associatedClock clock
set_interface_property audio_right_channel_source associatedReset reset
set_interface_property audio_right_channel_source dataBitsPerSymbol 8
set_interface_property audio_right_channel_source errorDescriptor ""
set_interface_property audio_right_channel_source firstSymbolInHighOrderBits true
set_interface_property audio_right_channel_source maxChannel 0
set_interface_property audio_right_channel_source readyLatency 0
set_interface_property audio_right_channel_source ENABLED true
set_interface_property audio_right_channel_source EXPORT_OF ""
set_interface_property audio_right_channel_source PORT_NAME_MAP ""
set_interface_property audio_right_channel_source CMSIS_SVD_VARIABLES ""
set_interface_property audio_right_channel_source SVD_ADDRESS_GROUP ""

add_interface_port audio_right_channel_source to_audio_right_channel_data data Output 24
add_interface_port audio_right_channel_source to_audio_right_channel_ready ready Input 1
add_interface_port audio_right_channel_source to_audio_right_channel_valid valid Output 1


# 
# connection point avalon_audio_sink
# 
add_interface avalon_audio_sink avalon_streaming end
set_interface_property avalon_audio_sink associatedClock clock
set_interface_property avalon_audio_sink associatedReset reset
set_interface_property avalon_audio_sink dataBitsPerSymbol 8
set_interface_property avalon_audio_sink errorDescriptor ""
set_interface_property avalon_audio_sink firstSymbolInHighOrderBits true
set_interface_property avalon_audio_sink maxChannel 0
set_interface_property avalon_audio_sink readyLatency 0
set_interface_property avalon_audio_sink ENABLED true
set_interface_property avalon_audio_sink EXPORT_OF ""
set_interface_property avalon_audio_sink PORT_NAME_MAP ""
set_interface_property avalon_audio_sink CMSIS_SVD_VARIABLES ""
set_interface_property avalon_audio_sink SVD_ADDRESS_GROUP ""

add_interface_port avalon_audio_sink audio_sink_data data Input 48
add_interface_port avalon_audio_sink audio_sink_ready ready Output 1
add_interface_port avalon_audio_sink audio_sink_valid valid Input 1


# 
# connection point avalon_audio_source
# 
add_interface avalon_audio_source avalon_streaming start
set_interface_property avalon_audio_source associatedClock clock
set_interface_property avalon_audio_source associatedReset reset
set_interface_property avalon_audio_source dataBitsPerSymbol 8
set_interface_property avalon_audio_source errorDescriptor ""
set_interface_property avalon_audio_source firstSymbolInHighOrderBits true
set_interface_property avalon_audio_source maxChannel 0
set_interface_property avalon_audio_source readyLatency 0
set_interface_property avalon_audio_source ENABLED true
set_interface_property avalon_audio_source EXPORT_OF ""
set_interface_property avalon_audio_source PORT_NAME_MAP ""
set_interface_property avalon_audio_source CMSIS_SVD_VARIABLES ""
set_interface_property avalon_audio_source SVD_ADDRESS_GROUP ""

add_interface_port avalon_audio_source audio_source_data data Output 48
add_interface_port avalon_audio_source audio_source_valid valid Output 1
add_interface_port avalon_audio_source audio_source_ready ready Input 1

