# TCL File Generated by Component Editor 17.1
# Tue Dec 12 21:03:18 CET 2017
# DO NOT MODIFY


# 
# request TCL package from ACDS 16.1
# 
package require -exact qsys 16.1


# 
# module WhiteNoise
# 
set_module_property DESCRIPTION "White Noise Generation with an LFSR"
set_module_property NAME WhiteNoise
set_module_property VERSION 1.0
set_module_property INTERNAL false
set_module_property OPAQUE_ADDRESS_MAP true
set_module_property GROUP "ASP-SoC IP/Dsp"
set_module_property AUTHOR "Franz Steinbacher"
set_module_property DISPLAY_NAME "WhiteNoise: White Noise Generator"
set_module_property INSTANTIATE_IN_SYSTEM_MODULE true
set_module_property EDITABLE false
set_module_property REPORT_TO_TALKBACK false
set_module_property ALLOW_GREYBOX_GENERATION false
set_module_property REPORT_HIERARCHY false

set_module_property ELABORATION_CALLBACK elaborate


# 
# file sets
# 
add_fileset QUARTUS_SYNTH QUARTUS_SYNTH "" ""
set_fileset_property QUARTUS_SYNTH TOP_LEVEL WhiteNoise
set_fileset_property QUARTUS_SYNTH ENABLE_RELATIVE_INCLUDE_PATHS false
set_fileset_property QUARTUS_SYNTH ENABLE_FILE_OVERWRITE_MODE false
add_fileset_file fixed_float_types_c.vhdl VHDL PATH ../../../grpPackages/pkgFixed/src/fixed_float_types_c.vhdl
add_fileset_file fixed_pkg_c.vhdl VHDL PATH ../../../grpPackages/pkgFixed/src/fixed_pkg_c.vhdl
add_fileset_file lfsr-p.vhd VHDL PATH ../../../grpPackages/pkgLfsr/src/lfsr-p.vhd
add_fileset_file WhiteNoise-ea.vhd VHDL PATH ../hdl/WhiteNoise-ea.vhd TOP_LEVEL_FILE

add_fileset SIM_VHDL SIM_VHDL "" ""
set_fileset_property SIM_VHDL TOP_LEVEL WhiteNoise
set_fileset_property SIM_VHDL ENABLE_RELATIVE_INCLUDE_PATHS false
set_fileset_property SIM_VHDL ENABLE_FILE_OVERWRITE_MODE false
add_fileset_file fixed_float_types_c.vhdl VHDL PATH ../../../grpPackages/pkgFixed/src/fixed_float_types_c.vhdl
add_fileset_file fixed_pkg_c.vhdl VHDL PATH ../../../grpPackages/pkgFixed/src/fixed_pkg_c.vhdl
add_fileset_file lfsr-p.vhd VHDL PATH ../../../grpPackages/pkgLfsr/src/lfsr-p.vhd
add_fileset_file WhiteNoise-ea.vhd VHDL PATH ../hdl/WhiteNoise-ea.vhd


# 
# parameters
# 
add_parameter data_width_g NATURAL 24
set_parameter_property data_width_g DEFAULT_VALUE 24
set_parameter_property data_width_g DISPLAY_NAME "Data Width"
set_parameter_property data_width_g TYPE NATURAL
set_parameter_property data_width_g UNITS bits
set_parameter_property data_width_g ALLOWED_RANGES {16 20 24 32}
set_parameter_property data_width_g HDL_PARAMETER true

add_parameter lfsr_length_g NATURAL 24
set_parameter_property lfsr_length_g DEFAULT_VALUE 24
set_parameter_property lfsr_length_g DISPLAY_NAME "LFSR Width"
set_parameter_property lfsr_length_g TYPE NATURAL
set_parameter_property lfsr_length_g ALLOWED_RANGES 16:168
set_parameter_property lfsr_length_g UNITS bits
set_parameter_property lfsr_length_g HDL_PARAMETER true

proc elaborate {} {
    set data_width [ get_parameter_value "data_width_g" ]
    set lfsr_width [ get_parameter_value "lfsr_length_g" ]

    if {$data_width > $lfsr_width} {
	send_message { Error Text } "lfsr width $lfsr_width must be greater or equal to data width $data_width !"
    }
}


# 
# display items
# 


# 
# connection point clock
# 
add_interface clock clock end
set_interface_property clock clockRate 0
set_interface_property clock ENABLED true
set_interface_property clock EXPORT_OF ""
set_interface_property clock PORT_NAME_MAP ""
set_interface_property clock CMSIS_SVD_VARIABLES ""
set_interface_property clock SVD_ADDRESS_GROUP ""

add_interface_port clock csi_clk clk Input 1


# 
# connection point reset
# 
add_interface reset reset end
set_interface_property reset associatedClock clock
set_interface_property reset synchronousEdges DEASSERT
set_interface_property reset ENABLED true
set_interface_property reset EXPORT_OF ""
set_interface_property reset PORT_NAME_MAP ""
set_interface_property reset CMSIS_SVD_VARIABLES ""
set_interface_property reset SVD_ADDRESS_GROUP ""

add_interface_port reset rsi_reset_n reset_n Input 1


# 
# connection point conduit_end_0
# 
add_interface conduit_end_0 conduit end
set_interface_property conduit_end_0 associatedClock clock
set_interface_property conduit_end_0 associatedReset ""
set_interface_property conduit_end_0 ENABLED true
set_interface_property conduit_end_0 EXPORT_OF ""
set_interface_property conduit_end_0 PORT_NAME_MAP ""
set_interface_property conduit_end_0 CMSIS_SVD_VARIABLES ""
set_interface_property conduit_end_0 SVD_ADDRESS_GROUP ""

add_interface_port conduit_end_0 coe_sample_strobe export Input 1


# 
# connection point s0_enable
# 
add_interface s0_enable avalon end
set_interface_property s0_enable addressUnits WORDS
set_interface_property s0_enable associatedClock clock
set_interface_property s0_enable associatedReset reset
set_interface_property s0_enable bitsPerSymbol 8
set_interface_property s0_enable burstOnBurstBoundariesOnly false
set_interface_property s0_enable burstcountUnits WORDS
set_interface_property s0_enable explicitAddressSpan 0
set_interface_property s0_enable holdTime 0
set_interface_property s0_enable linewrapBursts false
set_interface_property s0_enable maximumPendingReadTransactions 0
set_interface_property s0_enable maximumPendingWriteTransactions 0
set_interface_property s0_enable readLatency 0
set_interface_property s0_enable readWaitTime 1
set_interface_property s0_enable setupTime 0
set_interface_property s0_enable timingUnits Cycles
set_interface_property s0_enable writeWaitTime 0
set_interface_property s0_enable ENABLED true
set_interface_property s0_enable EXPORT_OF ""
set_interface_property s0_enable PORT_NAME_MAP ""
set_interface_property s0_enable CMSIS_SVD_VARIABLES ""
set_interface_property s0_enable SVD_ADDRESS_GROUP ""

add_interface_port s0_enable avs_s0_write write Input 1
add_interface_port s0_enable avs_s0_writedata writedata Input 32
set_interface_assignment s0_enable embeddedsw.configuration.isFlash 0
set_interface_assignment s0_enable embeddedsw.configuration.isMemoryDevice 0
set_interface_assignment s0_enable embeddedsw.configuration.isNonVolatileStorage 0
set_interface_assignment s0_enable embeddedsw.configuration.isPrintableDevice 0


# 
# connection point source
# 
add_interface source avalon_streaming start
set_interface_property source associatedClock clock
set_interface_property source associatedReset reset
set_interface_property source dataBitsPerSymbol 8
set_interface_property source errorDescriptor ""
set_interface_property source firstSymbolInHighOrderBits true
set_interface_property source maxChannel 0
set_interface_property source readyLatency 0
set_interface_property source ENABLED true
set_interface_property source EXPORT_OF ""
set_interface_property source PORT_NAME_MAP ""
set_interface_property source CMSIS_SVD_VARIABLES ""
set_interface_property source SVD_ADDRESS_GROUP ""

add_interface_port source aso_data data Output data_width_g
add_interface_port source aso_valid valid Output 1

