# TCL File Generated by Component Editor 16.1
# Tue Jun 13 10:38:58 CEST 2017
# DO NOT MODIFY


# 
# Delay "Delay" v1.0
# Michael Wurm 2017.06.13.10:38:58
# Unit delays left and right channel independent. Each channels delay can be configured separately.
# 

# 
# request TCL package from ACDS 16.1
# 
package require -exact qsys 16.1

# 
# module Delay
# 
set_module_property DESCRIPTION "Unit delays left and right channel independent. Each channel's delay can be configured separately."
set_module_property NAME Delay
set_module_property VERSION 1.0
set_module_property INTERNAL false
set_module_property OPAQUE_ADDRESS_MAP true
set_module_property GROUP "ASP-SoC IP/Audio"
set_module_property AUTHOR "Michael Wurm"
set_module_property DISPLAY_NAME Delay
set_module_property INSTANTIATE_IN_SYSTEM_MODULE true
set_module_property EDITABLE false
set_module_property REPORT_TO_TALKBACK false
set_module_property ALLOW_GREYBOX_GENERATION false
set_module_property REPORT_HIERARCHY false

# 
# file sets
# 
add_fileset QUARTUS_SYNTH QUARTUS_SYNTH "" ""
set_fileset_property QUARTUS_SYNTH TOP_LEVEL Delay
set_fileset_property QUARTUS_SYNTH ENABLE_RELATIVE_INCLUDE_PATHS false
set_fileset_property QUARTUS_SYNTH ENABLE_FILE_OVERWRITE_MODE false
add_fileset_file Delay-Bhv-a.vhd VHDL PATH ../hdl/Delay-Bhv-a.vhd
add_fileset_file Delay-e.vhd VHDL PATH ../hdl/Delay-e.vhd TOP_LEVEL_FILE
add_fileset_file ShiftRegRam-Rtl-a.vhd VHDL PATH ../../../grpUtils/unitShiftRegRam/src/ShiftRegRam-Rtl-a.vhd
add_fileset_file ShiftRegRam-e.vhd VHDL PATH ../../../grpUtils/unitShiftRegRam/src/ShiftRegRam-e.vhd

add_fileset SIM_VERILOG SIM_VERILOG "" ""
set_fileset_property SIM_VERILOG TOP_LEVEL Delay
set_fileset_property SIM_VERILOG ENABLE_RELATIVE_INCLUDE_PATHS false
set_fileset_property SIM_VERILOG ENABLE_FILE_OVERWRITE_MODE false
add_fileset_file Delay-Bhv-a.vhd VHDL PATH ../hdl/Delay-Bhv-a.vhd
add_fileset_file Delay-e.vhd VHDL PATH ../hdl/Delay-e.vhd
add_fileset_file ShiftRegRam-Rtl-a.vhd VHDL PATH ../../../grpUtils/unitShiftRegRam/src/ShiftRegRam-Rtl-a.vhd
add_fileset_file ShiftRegRam-e.vhd VHDL PATH ../../../grpUtils/unitShiftRegRam/src/ShiftRegRam-e.vhd


# 
# parameters
# 
add_parameter gMaxDelay NATURAL 100
set_parameter_property gMaxDelay DEFAULT_VALUE 100
set_parameter_property gMaxDelay DISPLAY_NAME gMaxDelay
set_parameter_property gMaxDelay DESCRIPTION \
    "Maximum delay that can be reached."
set_parameter_property gMaxDelay LONG_DESCRIPTION \
    "Maximum delay that can be reached."
set_parameter_property gMaxDelay TYPE NATURAL
set_parameter_property gMaxDelay UNITS Milliseconds
set_parameter_property gMaxDelay ALLOWED_RANGES 1:100
set_parameter_property gMaxDelay HDL_PARAMETER true

add_parameter gNewDataFreq NATURAL 48000
set_parameter_property gNewDataFreq DEFAULT_VALUE 48000
set_parameter_property gNewDataFreq DISPLAY_NAME gNewDataFreq
set_parameter_property gNewDataFreq DESCRIPTION \
	"frequency, with which new data blocks arrive"
set_parameter_property gNewDataFreq LONG_DESCRIPTION \
	"frequency, with which new data blocks arrive"
set_parameter_property gNewDataFreq TYPE NATURAL
set_parameter_property gNewDataFreq UNITS Hertz
set_parameter_property gNewDataFreq ALLOWED_RANGES {32000 48000 96000}
set_parameter_property gNewDataFreq HDL_PARAMETER true

add_parameter gDataWidth NATURAL 24
set_parameter_property gDataWidth DEFAULT_VALUE 24
set_parameter_property gDataWidth DISPLAY_NAME gDataWidth
set_parameter_property gDataWidth DESCRIPTION \
	"bitwidth of single register"
set_parameter_property gDataWidth LONG_DESCRIPTION \
	"bitwidth of single register"
set_parameter_property gDataWidth TYPE NATURAL
set_parameter_property gDataWidth UNITS bits
set_parameter_property gDataWidth ALLOWED_RANGES {16 24 32}
set_parameter_property gDataWidth HDL_PARAMETER true


# 
# display items
# 


# 
# connection point clock
# 
add_interface clock clock end
set_interface_property clock clockRate 0
set_interface_property clock ENABLED true
set_interface_property clock EXPORT_OF ""
set_interface_property clock PORT_NAME_MAP ""
set_interface_property clock CMSIS_SVD_VARIABLES ""
set_interface_property clock SVD_ADDRESS_GROUP ""

add_interface_port clock csi_clk clk Input 1


# 
# connection point s0
# 
add_interface s0 avalon end
set_interface_property s0 addressUnits WORDS
set_interface_property s0 associatedClock clock
set_interface_property s0 associatedReset reset_n
set_interface_property s0 bitsPerSymbol 8
set_interface_property s0 burstOnBurstBoundariesOnly false
set_interface_property s0 burstcountUnits WORDS
set_interface_property s0 explicitAddressSpan 0
set_interface_property s0 holdTime 0
set_interface_property s0 linewrapBursts false
set_interface_property s0 maximumPendingReadTransactions 0
set_interface_property s0 maximumPendingWriteTransactions 0
set_interface_property s0 readLatency 0
set_interface_property s0 readWaitTime 1
set_interface_property s0 setupTime 0
set_interface_property s0 timingUnits Cycles
set_interface_property s0 writeWaitTime 0
set_interface_property s0 ENABLED true
set_interface_property s0 EXPORT_OF ""
set_interface_property s0 PORT_NAME_MAP ""
set_interface_property s0 CMSIS_SVD_VARIABLES ""
set_interface_property s0 SVD_ADDRESS_GROUP ""

add_interface_port s0 avs_s0_write write Input 1
add_interface_port s0 avs_s0_address address Input 3
add_interface_port s0 avs_s0_writedata writedata Input 32
add_interface_port s0 avs_s0_readdata readdata Output 32
set_interface_assignment s0 embeddedsw.configuration.isFlash 0
set_interface_assignment s0 embeddedsw.configuration.isMemoryDevice 0
set_interface_assignment s0 embeddedsw.configuration.isNonVolatileStorage 0
set_interface_assignment s0 embeddedsw.configuration.isPrintableDevice 0


# 
# connection point as_sink_left
# 
add_interface as_sink_left avalon_streaming end
set_interface_property as_sink_left associatedClock clock
set_interface_property as_sink_left associatedReset reset_n
set_interface_property as_sink_left dataBitsPerSymbol 8
set_interface_property as_sink_left errorDescriptor ""
set_interface_property as_sink_left firstSymbolInHighOrderBits true
set_interface_property as_sink_left maxChannel 0
set_interface_property as_sink_left readyLatency 0
set_interface_property as_sink_left ENABLED true
set_interface_property as_sink_left EXPORT_OF ""
set_interface_property as_sink_left PORT_NAME_MAP ""
set_interface_property as_sink_left CMSIS_SVD_VARIABLES ""
set_interface_property as_sink_left SVD_ADDRESS_GROUP ""

add_interface_port as_sink_left asi_left_data data Input gdatawidth
add_interface_port as_sink_left asi_left_valid valid Input 1


# 
# connection point as_sink_right
# 
add_interface as_sink_right avalon_streaming end
set_interface_property as_sink_right associatedClock clock
set_interface_property as_sink_right associatedReset reset_n
set_interface_property as_sink_right dataBitsPerSymbol 8
set_interface_property as_sink_right errorDescriptor ""
set_interface_property as_sink_right firstSymbolInHighOrderBits true
set_interface_property as_sink_right maxChannel 0
set_interface_property as_sink_right readyLatency 0
set_interface_property as_sink_right ENABLED true
set_interface_property as_sink_right EXPORT_OF ""
set_interface_property as_sink_right PORT_NAME_MAP ""
set_interface_property as_sink_right CMSIS_SVD_VARIABLES ""
set_interface_property as_sink_right SVD_ADDRESS_GROUP ""

add_interface_port as_sink_right asi_right_data data Input gdatawidth
add_interface_port as_sink_right asi_right_valid valid Input 1


# 
# connection point as_source_left
# 
add_interface as_source_left avalon_streaming start
set_interface_property as_source_left associatedClock clock
set_interface_property as_source_left associatedReset reset_n
set_interface_property as_source_left dataBitsPerSymbol 8
set_interface_property as_source_left errorDescriptor ""
set_interface_property as_source_left firstSymbolInHighOrderBits true
set_interface_property as_source_left maxChannel 0
set_interface_property as_source_left readyLatency 0
set_interface_property as_source_left ENABLED true
set_interface_property as_source_left EXPORT_OF ""
set_interface_property as_source_left PORT_NAME_MAP ""
set_interface_property as_source_left CMSIS_SVD_VARIABLES ""
set_interface_property as_source_left SVD_ADDRESS_GROUP ""

add_interface_port as_source_left aso_left_data data Output gdatawidth
add_interface_port as_source_left aso_left_valid valid Output 1


# 
# connection point as_source_right
# 
add_interface as_source_right avalon_streaming start
set_interface_property as_source_right associatedClock clock
set_interface_property as_source_right associatedReset reset_n
set_interface_property as_source_right dataBitsPerSymbol 8
set_interface_property as_source_right errorDescriptor ""
set_interface_property as_source_right firstSymbolInHighOrderBits true
set_interface_property as_source_right maxChannel 0
set_interface_property as_source_right readyLatency 0
set_interface_property as_source_right ENABLED true
set_interface_property as_source_right EXPORT_OF ""
set_interface_property as_source_right PORT_NAME_MAP ""
set_interface_property as_source_right CMSIS_SVD_VARIABLES ""
set_interface_property as_source_right SVD_ADDRESS_GROUP ""

add_interface_port as_source_right aso_right_data data Output gdatawidth
add_interface_port as_source_right aso_right_valid valid Output 1


# 
# connection point reset_n
# 
add_interface reset_n reset end
set_interface_property reset_n associatedClock clock
set_interface_property reset_n synchronousEdges DEASSERT
set_interface_property reset_n ENABLED true
set_interface_property reset_n EXPORT_OF ""
set_interface_property reset_n PORT_NAME_MAP ""
set_interface_property reset_n CMSIS_SVD_VARIABLES ""
set_interface_property reset_n SVD_ADDRESS_GROUP ""

add_interface_port reset_n rsi_reset_n reset_n Input 1

